const PRODUCT_LIST_REQUEST: string = "PRODUCT_LIST_REQUEST";
const PRODUCT_LIST_SUCCESS: string = "PRODUCT_LIST_SUCCESS";
const PRODUCT_LIST_FAIL: string = "PRODUCT_LIST_FAIL";

export { PRODUCT_LIST_REQUEST, PRODUCT_LIST_SUCCESS, PRODUCT_LIST_FAIL };
