const PRODUCT_LIST_REQUEST: string = "PRODUCT_LIST_REQUEST";
const PRODUCT_LIST_SUCCESS: string = "PRODUCT_LIST_SUCCESS";
const PRODUCT_LIST_FAIL: string = "PRODUCT_LIST_FAIL";

const PRODUCT_DETAILS_REQUEST: string = "PRODUCT_DETAILS_REQUEST";
const PRODUCT_DETAILS_SUCCESS: string = "PRODUCT_DETAILS_SUCCESS";
const PRODUCT_DETAILS_FAIL: string = "PRODUCT_DETAILS_FAIL";

const CART_ADD_ITEM: string = "CART_ADD_ITEM";
const CART_ADD_SUCCESS: string = "CART_ADD_SUCCESS";
const CART_ADD_FAIL: string = "CART_ADD_FAIL";

const CART_REMOVE_ITEM: string = "CART_REMOVE_ITEM";

const CART_SAVE_SHIPPING_ADDRESS: string = "CART_SAVE_SHIPPING_ADDRESS";

const USER_LOGIN_REQUEST: string = "USER_LOGIN_REQUEST";
const USER_LOGIN_SUCCESS: string = "USER_LOGIN_SUCCESS";
const USER_LOGIN_FAIL: string = "USER_LOGIN_FAIL";

const USER_LOGOUT = "USER_LOGOUT";

const USER_REGISTER_REQUEST: string = "USER_REGISTER_REQUEST";
const USER_REGISTER_SUCCESS: string = "USER_REGISTER_SUCCESS";
const USER_REGISTER_FAIL: string = "USER_REGISTER_FAIL";

const USER_GET_PROFILE_REQUEST: string = "USER_GET_PROFILE_REQUEST";
const USER_GET_PROFILE_SUCCESS: string = "USER_GET_PROFILE_SUCCESS";
const USER_GET_PROFILE_FAIL: string = "USER_GET_PROFILE_FAIL";

const USER_UPDATE_PROFILE_REQUEST: string = "USER_UPDATE_PROFILE_REQUEST";
const USER_UPDATE_PROFILE_SUCCESS: string = "USER_UPDATE_PROFILE_SUCCESS";
const USER_UPDATE_PROFILE_FAIL: string = "USER_UPDATE_PROFILE_FAIL";
const CART_SAVE_PAYMENT_METHOD: string = "CART_SAVE_PAYMENT_METHOD";

const ORDER_CREATE_REQUEST: string = "ORDER_CREATE_REQUEST";
const ORDER_CREATE_SUCCESS: string = "ORDER_CREATE_SUCCESS";
const ORDER_CREATE_FAIL: string = "ORDER_CREATE_FAIL";

const ORDER_DETAILS_REQUEST: string = "ORDER_DETAILS_REQUEST";
const ORDER_DETAILS_SUCCESS: string = "ORDER_DETAILS_SUCCESS";
const ORDER_DETAILS_FAIL: string = "ORDER_DETAILS_FAIL";

const ORDER_PAY_REQUEST: string = "ORDER_PAY_REQUEST";
const ORDER_PAY_SUCCESS: string = "ORDER_PAY_SUCCESS";
const ORDER_PAY_FAIL: string = "ORDER_PAY_FAIL";
const ORDER_PAY_RESET: string = "ORDER_PAY_RESET";

export {
  PRODUCT_LIST_REQUEST,
  PRODUCT_LIST_SUCCESS,
  PRODUCT_LIST_FAIL,
  PRODUCT_DETAILS_REQUEST,
  PRODUCT_DETAILS_SUCCESS,
  PRODUCT_DETAILS_FAIL,
  CART_ADD_ITEM,
  CART_ADD_SUCCESS,
  CART_ADD_FAIL,
  CART_REMOVE_ITEM,
  USER_LOGIN_REQUEST,
  USER_LOGIN_SUCCESS,
  USER_LOGIN_FAIL,
  USER_LOGOUT,
  USER_REGISTER_REQUEST,
  USER_REGISTER_SUCCESS,
  USER_REGISTER_FAIL,
  USER_GET_PROFILE_REQUEST,
  USER_GET_PROFILE_SUCCESS,
  USER_GET_PROFILE_FAIL,
  USER_UPDATE_PROFILE_REQUEST,
  USER_UPDATE_PROFILE_SUCCESS,
  USER_UPDATE_PROFILE_FAIL,
  CART_SAVE_SHIPPING_ADDRESS,
  CART_SAVE_PAYMENT_METHOD,
  ORDER_CREATE_REQUEST,
  ORDER_CREATE_SUCCESS,
  ORDER_CREATE_FAIL,
  ORDER_DETAILS_REQUEST,
  ORDER_DETAILS_SUCCESS,
  ORDER_DETAILS_FAIL,
  ORDER_PAY_REQUEST,
  ORDER_PAY_SUCCESS,
  ORDER_PAY_FAIL,
  ORDER_PAY_RESET,
};
